- hosts: dom_pepspmt
  environment:
    http_proxy: http://proxy_centrale:3128
    https_proxy: http://proxy_centrale:3128
  roles:
     - { role: jre, jre_ver: 8u91 }
     - { role: tomcat, tomcat_ver: 8.0.32 }
     - role: logreader
     - role: oem
     - tomcat-instance
  sudo: yes
